### ISSUE TITLE
Listen to events

### ISSUE THREAD

**Issue by creazy231** [Paperchain/nuxt-box#1]
Hey there,
Im using the nuxt-box and Im very satisfied with it.
Now I want to listen to **events** my contract emits but I cant find any solution how to do this.

That's wat I tried without success:
```
this.$store.state.myContract.events.MyEvent({fromBlock: 0, toBlock: 'latest'}, (err, event) => {
                if (err) console.log(err);
                console.log(event);
            }).on('data', function(event){
                console.log(event);
            }).on('changed', function(event){
                console.log('on changed');
            }).on('error', console.error);
```

Anyone here could give me a small example?
Thanks a lot :)

**Comment by pyyding** [comment]
Thanks for the positive comments!

MetaMask doesn't support web sockets right now but they're getting close. This means we can't watch these events by default yet.

This guy had the same issue: 
https://github.com/MetaMask/metamask-extension/issues/2601

For a hacky solution you can check out this thread:
https://github.com/MetaMask/metamask-extension/issues/3642#issuecomment-379921721

**Comment by rahulrumalla** [comment]
@creazy231 I did some digging around. The problem is with the connection to web3. The out-of-box solution connects to web3 using json-rpc over http. Since we need listen to event as they're emitted, we need to persist that connection, meaning a websocket endpoint is needed. 

This change needs to happen at https://github.com/Paperchain/nuxt-box/blob/master/src/plugins/web3.js

```js
web3.setProvider(new Web3.providers.WebsocketProvider('ws://localhost:8546'));

// or use infura
web3.setProvider(new Web3.providers.WebsocketProvider('wss://mainnet.infura.io/_ws'));
```

You can also use the local geth ipc, recommended as the most secure way. 
```js
// Using the IPC provider in node.js
var net = require('net');
var web3 = new Web3('/Users/myuser/Library/Ethereum/geth.ipc', net); // mac os path
```

I haven't tested the above code out yet. But if you do try it, please update us :) Hope this helps for now.

**Comment by creazy231** [comment]
@rahulrumalla thanks a lot for your accomplished answer. I successfully manage the events via websockets now doing the following:
For everything except events I register my provider with the following code:
`const instance = new Web3(Web3.givenProvider || 'http://localhost:8546');`

and to listen to events I created a separate instance with the following code:
`const instance = new Web3('ws://localhost:8546');`

therewith Im able to listen to events like so:
```
    this.$store.state.theContract.web3Events.events.MyEvent({}, (error, data) => {
        if (error)
            console.log("Error: " + error);
        else
            console.log("Log data:");
            console.log(data);
    });
```

**Comment by rahulrumalla** [comment]
@creazy231 Awesome, stuff! Thanks for giving us the update. :)

**Comment by creazy231** [comment]
@rahulrumalla no problem :) just took me half a day to figure out how to listen to events :D the reason why it took me so long was, that there are sooo many code examples out there showing working solutions with the OLD version of web3 and Im supposed to use the newest version

hopefully I can help some people with my solution :)
And of cause your solution would work, too. (well its the same in general with other code) 👍
